# Generated by Django 5.1.4 on 2024-12-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='Created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='Created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='Original_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='Product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='Selling_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='trending',
            new_name='Trending',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='Vendor',
        ),
    ]
