# Generated by Django 5.1.4 on 2024-12-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_quantity',
            new_name='product_qty',
        ),
    ]
